# Slack
---
handler: SlackService

slack:
  - botid: xoxb-xxx
    identifier: dmitriid
    ignore:
      - username: fluor
        bot: true
    channels:
      - general
      - random
  - botid: xoxb-xxx
    identifier: erlyclub
    ignore:
      - username: fluor
        bot: true
    channels:
      - random

transformations:
  - TransformSlackUsers
  - TransformSlackChannels

mqtt:
  clientid: slack-firehose
  broker: tcp://localhost:1883
  firehose:
    topic: firehose
    qos: 0
  subscribe:
    topic: to-slack
    qos: 0
