# Sample configuration for Slack firehose
---
slack:
  botid: xoxb-xxx
  identifier: id
  channels:
    - general
    - random

mqtt:
  publish:
    topic: firehose
    clientid: slack-firehose
    broker: tcp://localhost:1883
    qos: 0
  subscribe:
    topic: to-slack
