# Telegram -> Slack
---
handler: MappingService

mapping:
  - from_service: "-1001050383488"
    from_type: telegram
    from_subtype: post
    to_service: dmitriid
    to_channel: random
    short_username: false
  - from_service: "-1001066864434"
    from_type: telegram
    from_subtype: post
    to_service: erlyclub
    to_channel: random
    short_username: false

mqtt:
  clientid: tsm
  broker: tcp://localhost:1883
  subscribe:
    topic: firehose
    qos: 0
  firehose:
    topic: to-slack
    qos: 0
