# Configuration for xmpp firehose
---
xmpp:
  service_domain: jabber.ru
  chat_service: conference.jabber.ru
  username: u
  password: p
  resource: firehose
  ignore:
    - fluor@jabber.ru
  rooms:
    - "some-room"

mqtt:
  topic: firehose
  clientid: xmpp-firehose
  broker: tcp://localhost:1883
  qos: 0
